version: '3'
services:
  app:
    container_name: push_server
    restart: always
    build: .
    ports:
      - '7054:7054'
# networks:
#   default:
#     external:
#       name: buroplatform_default